# Generated by Django 4.2.5 on 2023-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0002_permission_is_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="icon",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="图标"
            ),
        ),
    ]
