# Generated by Django 4.2.5 on 2023-09-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0004_menu_remove_permission_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="pid",
            field=models.ForeignKey(
                blank=True,
                help_text="对于非菜单权限需要选择一个可以成为菜单的权限，用户做默认展开",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parents",
                to="rbac.permission",
                verbose_name="关联的权限",
            ),
        ),
    ]
