# Generated by Django 4.2.5 on 2023-09-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0005_permission_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="name",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="url的别名"
            ),
        ),
    ]
