# Generated by Django 4.2.5 on 2023-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0006_permission_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="icon",
            field=models.CharField(default=1, max_length=32, verbose_name="图标"),
            preserve_default=False,
        ),
    ]
